Script started on Wednesday 05 July 2017 12:36:08 PM IST
[1m[7m%[27m[1m[0m                                                                                ]2;karan@karUbuntu: ~/djangoSandbox/trydjango19]1;..x/trydjango19[0m[27m[24m[J[01;32mâžœ  [36mtrydjango19[00m [K[?1h=[?2004hssource bin[1m/[0m[0m/activate[?1l>[?2004l
]2;source bin/activate]1;source[1m[7m%[27m[1m[0m                                                                                ]2;karan@karUbuntu: ~/djangoSandbox/trydjango19]1;..x/trydjango19[0m[27m[24m[J(trydjango19) [01;32mâžœ  [36mtrydjango19[00m [K[?1h=[?2004hppython ma      p  lls[?1l>[?2004l
]2;ls --color=tty]1;ls[0m[01;34mbin[0m  [01;34minclude[0m  [01;34mlib[0m  pip-selfcheck.json  [01;34msrc[0m  trydjango192.log
[1m[7m%[27m[1m[0m                                                                                ]2;karan@karUbuntu: ~/djangoSandbox/trydjango19]1;..x/trydjango19[0m[27m[24m[J(trydjango19) [01;32mâžœ  [36mtrydjango19[00m [K[?1h=[?2004hccd c  ccd ..[?1l>[?2004l
]2;cd ..]1;cd[1m[7m%[27m[1m[0m                                                                                ]2;karan@karUbuntu: ~/djangoSandbox]1;~/djangoSandbox[0m[27m[24m[J(trydjango19) [01;32mâžœ  [36mdjangoSandbox[00m [K[?1h=[?2004hccd trydjango19[1m/[0m[0m [?1l>[?2004l
]2;cd trydjango19]1;cd[1m[7m%[27m[1m[0m                                                                                ]2;karan@karUbuntu: ~/djangoSandbox/trydjango19]1;..x/trydjango19[0m[27m[24m[J(trydjango19) [01;32mâžœ  [36mtrydjango19[00m [K[?1h=[?2004hlls[?1l>[?2004l
]2;ls --color=tty]1;ls[0m[01;34mbin[0m  [01;34minclude[0m  [01;34mlib[0m  pip-selfcheck.json  [01;34msrc[0m  trydjango192.log
[1m[7m%[27m[1m[0m                                                                                ]2;karan@karUbuntu: ~/djangoSandbox/trydjango19]1;..x/trydjango19[0m[27m[24m[J(trydjango19) [01;32mâžœ  [36mtrydjango19[00m [K[?1h=[?2004hccd src[1m/[0m[0m [?1l>[?2004l
]2;cd src]1;cd[1m[7m%[27m[1m[0m                                                                                ]2;karan@karUbuntu: ~/djangoSandbox/trydjango19/src]1;..ydjango19/src[0m[27m[24m[J(trydjango19) [01;32mâžœ  [36msrc[00m [K[?1h=[?2004hlls[?1l>[?2004l
]2;ls --color=tty]1;lsdb.sqlite3  [0m[01;32mmanage.py[0m  [01;34mtrydjango19[0m
[1m[7m%[27m[1m[0m                                                                                ]2;karan@karUbuntu: ~/djangoSandbox/trydjango19/src]1;..ydjango19/src[0m[27m[24m[J(trydjango19) [01;32mâžœ  [36msrc[00m [K[?1h=[?2004hppython manage.py[1m [0m[0m startapp posts[?1l>[?2004l
]2;python manage.py startapp posts]1;python[1m[7m%[27m[1m[0m                                                                                ]2;karan@karUbuntu: ~/djangoSandbox/trydjango19/src]1;..ydjango19/src[0m[27m[24m[J(trydjango19) [01;32mâžœ  [36msrc[00m [K[?1h=[?2004hppython --version[?1l>[?2004l
]2;python --version]1;pythonPython 3.5.3
[1m[7m%[27m[1m[0m                                                                                ]2;karan@karUbuntu: ~/djangoSandbox/trydjango19/src]1;..ydjango19/src[0m[27m[24m[J(trydjango19) [01;32mâžœ  [36msrc[00m [K[?1h=[?2004hppython n manage.py migrate[1m [0m[0m [?1l>[?2004l
]2;python manage.py migrate]1;python[31;1mSystemCheckError: System check identified some issues:
[0m
ERRORS:
[31;1mposts.Post.title: (fields.E120) CharFields must define a 'max_length' attribute.[0m
[1m[7m%[27m[1m[0m                                                                                ]2;karan@karUbuntu: ~/djangoSandbox/trydjango19/src]1;..ydjango19/src[0m[27m[24m[J(trydjango19) [01;31mâžœ  [36msrc[00m [K[?1h=[?2004hpython manage.py migrate[?1l>[?2004l
]2;python manage.py migrate]1;python[36;1mOperations to perform:[0m
[1m  Apply all migrations: [0madmin, auth, contenttypes, sessions
[36;1mRunning migrations:[0m
  No migrations to apply.
[31m  Your models have changes that are not yet reflected in a migration, and so won't be applied.[0m
[31m  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.[0m
[1m[7m%[27m[1m[0m                                                                                ]2;karan@karUbuntu: ~/djangoSandbox/trydjango19/src]1;..ydjango19/src[0m[27m[24m[J(trydjango19) [01;32mâžœ  [36msrc[00m [K[?1h=[?2004hpython manage.py migrate[1Cmigrateamigratekmigrateemigrate[1C[1C[1C[1C[1C[1C[1C ions[?1l>[?2004l
]2;python manage.py makemigrations]1;python[36;1mMigrations for 'posts':[0m
  [1mposts/migrations/0001_initial.py[0m
    - Create model Post
[1m[7m%[27m[1m[0m                                                                                ]2;karan@karUbuntu: ~/djangoSandbox/trydjango19/src]1;..ydjango19/src[0m[27m[24m[J(trydjango19) [01;32mâžœ  [36msrc[00m [K[?1h=[?2004hpython manage.py makemigrations[13Digrate       [?1l>[?2004l
]2;python manage.py migrate]1;python[36;1mOperations to perform:[0m
[1m  Apply all migrations: [0madmin, auth, contenttypes, posts, sessions
[36;1mRunning migrations:[0m
  Applying posts.0001_initial...[32;1m OK[0m
[1m[7m%[27m[1m[0m                                                                                ]2;karan@karUbuntu: ~/djangoSandbox/trydjango19/src]1;..ydjango19/src[0m[27m[24m[J(trydjango19) [01;32mâžœ  [36msrc[00m [K[?1h=[?2004hpython manage.py migrate[?1l>[?2004l
]2;python manage.py migrate]1;python[36;1mOperations to perform:[0m
[1m  Apply all migrations: [0madmin, auth, contenttypes, posts, sessions
[36;1mRunning migrations:[0m
  No migrations to apply.
[1m[7m%[27m[1m[0m                                                                                ]2;karan@karUbuntu: ~/djangoSandbox/trydjango19/src]1;..ydjango19/src[0m[27m[24m[J(trydjango19) [01;32mâžœ  [36msrc[00m [K[?1h=[?2004hpython manage.py migrateakemigrations[13Digrate       akemigrations[13Digrate              runserver[?1l>[?2004l
]2;python manage.py runserver]1;pythonPerforming system checks...

System check identified no issues (0 silenced).
July 05, 2017 - 07:35:26
Django version 1.11.3, using settings 'trydjango19.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[05/Jul/2017 07:35:32] [m"GET /admin/auth/user/ HTTP/1.1" 200 6866[0m
[05/Jul/2017 07:35:32] [36m"GET /static/admin/css/base.css HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:32] [36m"GET /static/admin/js/core.js HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:32] [36m"GET /static/admin/css/changelists.css HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:32] [36m"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:32] [m"GET /admin/jsi18n/ HTTP/1.1" 200 3189[0m
[05/Jul/2017 07:35:32] [36m"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:32] [36m"GET /static/admin/js/actions.js HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:32] [36m"GET /static/admin/js/urlify.js HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:32] [36m"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:32] [36m"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:32] [36m"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:32] [36m"GET /static/admin/img/search.svg HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:32] [36m"GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:32] [36m"GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:32] [36m"GET /static/admin/css/fonts.css HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:32] [36m"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:32] [36m"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:32] [36m"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:32] [36m"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:32] [36m"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:36] [m"GET /admin/auth/ HTTP/1.1" 200 2705[0m
[05/Jul/2017 07:35:36] [36m"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:36] [36m"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:36] [36m"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:39] [m"GET /admin/ HTTP/1.1" 200 3713[0m
[05/Jul/2017 07:35:42] [m"GET /admin/posts/post/add/ HTTP/1.1" 200 4299[0m
[05/Jul/2017 07:35:43] [36m"GET /static/admin/css/forms.css HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:43] [m"GET /admin/jsi18n/ HTTP/1.1" 200 3189[0m
[05/Jul/2017 07:35:43] [36m"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:43] [36m"GET /static/admin/js/change_form.js HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:43] [36m"GET /static/admin/css/widgets.css HTTP/1.1" 304 0[0m
[05/Jul/2017 07:35:52] [32m"POST /admin/posts/post/add/ HTTP/1.1" 302 0[0m
[05/Jul/2017 07:35:52] [m"GET /admin/posts/post/ HTTP/1.1" 200 4323[0m
[05/Jul/2017 07:35:52] [m"GET /admin/jsi18n/ HTTP/1.1" 200 3189[0m
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2017 - 08:01:59
Django version 1.11.3, using settings 'trydjango19.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[05/Jul/2017 08:02:04] [m"GET /admin/posts/post/ HTTP/1.1" 200 4609[0m
[05/Jul/2017 08:02:04] [36m"GET /static/admin/css/base.css HTTP/1.1" 304 0[0m
[05/Jul/2017 08:02:04] [36m"GET /static/admin/js/core.js HTTP/1.1" 304 0[0m
[05/Jul/2017 08:02:04] [36m"GET /static/admin/css/changelists.css HTTP/1.1" 304 0[0m
[05/Jul/2017 08:02:04] [m"GET /admin/jsi18n/ HTTP/1.1" 200 3189[0m
[05/Jul/2017 08:02:04] [36m"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0[0m
[05/Jul/2017 08:02:04] [36m"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0[0m
[05/Jul/2017 08:02:04] [36m"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0[0m
[05/Jul/2017 08:02:04] [36m"GET /static/admin/js/urlify.js HTTP/1.1" 304 0[0m
[05/Jul/2017 08:02:04] [36m"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0[0m
[05/Jul/2017 08:02:04] [36m"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0[0m
[05/Jul/2017 08:02:04] [36m"GET /static/admin/js/actions.js HTTP/1.1" 304 0[0m
[05/Jul/2017 08:02:04] [36m"GET /static/admin/css/fonts.css HTTP/1.1" 304 0[0m
[05/Jul/2017 08:02:04] [36m"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0[0m
[05/Jul/2017 08:02:04] [36m"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0[0m
[05/Jul/2017 08:02:04] [36m"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0[0m
[05/Jul/2017 08:02:04] [36m"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0[0m
[05/Jul/2017 08:02:05] [m"GET /admin/posts/post/ HTTP/1.1" 200 4609[0m
[05/Jul/2017 08:02:05] [m"GET /admin/jsi18n/ HTTP/1.1" 200 3189[0m
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2017 - 08:04:21
Django version 1.11.3, using settings 'trydjango19.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[05/Jul/2017 08:04:27] [m"GET /admin/posts/post/ HTTP/1.1" 200 6254[0m
[05/Jul/2017 08:04:27] [m"GET /admin/jsi18n/ HTTP/1.1" 200 3189[0m
[05/Jul/2017 08:04:33] [m"GET /admin/posts/post/?posted__gte=2017-07-05+00%3A00%3A00%2B00%3A00&posted__lt=2017-07-06+00%3A00%3A00%2B00%3A00 HTTP/1.1" 200 7315[0m
[05/Jul/2017 08:04:33] [m"GET /admin/jsi18n/ HTTP/1.1" 200 3189[0m
[05/Jul/2017 08:04:35] [m"GET /admin/posts/post/?posted__gte=2017-06-28+00%3A00%3A00%2B00%3A00&posted__lt=2017-07-06+00%3A00%3A00%2B00%3A00 HTTP/1.1" 200 7315[0m
[05/Jul/2017 08:04:35] [m"GET /admin/jsi18n/ HTTP/1.1" 200 3189[0m
[05/Jul/2017 08:04:37] [m"GET /admin/posts/post/?posted__gte=2017-01-01+00%3A00%3A00%2B00%3A00&posted__lt=2018-01-01+00%3A00%3A00%2B00%3A00 HTTP/1.1" 200 7315[0m
[05/Jul/2017 08:04:37] [m"GET /admin/jsi18n/ HTTP/1.1" 200 3189[0m
[05/Jul/2017 08:04:40] [m"GET /admin/posts/post/?last_updated__gte=2017-01-01+00%3A00%3A00%2B00%3A00&last_updated__lt=2018-01-01+00%3A00%3A00%2B00%3A00&posted__gte=2017-01-01+00%3A00%3A00%2B00%3A00&posted__lt=2018-01-01+00%3A00%3A00%2B00%3A00 HTTP/1.1" 200 8460[0m
[05/Jul/2017 08:04:40] [m"GET /admin/jsi18n/ HTTP/1.1" 200 3189[0m
[05/Jul/2017 08:04:43] [m"GET /admin/posts/post/?last_updated__gte=2017-07-05+00%3A00%3A00%2B00%3A00&last_updated__lt=2017-07-06+00%3A00%3A00%2B00%3A00&posted__gte=2017-01-01+00%3A00%3A00%2B00%3A00&posted__lt=2018-01-01+00%3A00%3A00%2B00%3A00 HTTP/1.1" 200 8460[0m
[05/Jul/2017 08:04:43] [m"GET /admin/jsi18n/ HTTP/1.1" 200 3189[0m
[05/Jul/2017 08:04:44] [m"GET /admin/posts/post/?last_updated__gte=2017-07-05+00%3A00%3A00%2B00%3A00&last_updated__lt=2017-07-06+00%3A00%3A00%2B00%3A00&posted__gte=2017-07-05+00%3A00%3A00%2B00%3A00&posted__lt=2017-07-06+00%3A00%3A00%2B00%3A00 HTTP/1.1" 200 8460[0m
[05/Jul/2017 08:04:44] [m"GET /admin/jsi18n/ HTTP/1.1" 200 3189[0m
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2017 - 08:12:25
Django version 1.11.3, using settings 'trydjango19.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[05/Jul/2017 08:12:29] [m"GET /admin/posts/post/?last_updated__gte=2017-07-05+00%3A00%3A00%2B00%3A00&last_updated__lt=2017-07-06+00%3A00%3A00%2B00%3A00&posted__gte=2017-07-05+00%3A00%3A00%2B00%3A00&posted__lt=2017-07-06+00%3A00%3A00%2B00%3A00 HTTP/1.1" 200 9848[0m
[05/Jul/2017 08:12:29] [36m"GET /static/admin/css/base.css HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:29] [36m"GET /static/admin/css/changelists.css HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:29] [36m"GET /static/admin/css/forms.css HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:29] [36m"GET /static/admin/js/core.js HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:29] [m"GET /admin/jsi18n/ HTTP/1.1" 200 3189[0m
[05/Jul/2017 08:12:29] [36m"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:29] [36m"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:29] [36m"GET /static/admin/js/urlify.js HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:29] [36m"GET /static/admin/js/actions.js HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:29] [36m"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:29] [36m"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:29] [36m"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:29] [36m"GET /static/admin/img/search.svg HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:29] [36m"GET /static/admin/css/fonts.css HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:29] [36m"GET /static/admin/css/widgets.css HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:29] [36m"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:29] [36m"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:29] [36m"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:29] [36m"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:34] [m"GET /admin/posts/post/?q=mutton&last_updated__gte=2017-07-05+00%3A00%3A00%2B00%3A00&posted__gte=2017-07-05+00%3A00%3A00%2B00%3A00&last_updated__lt=2017-07-06+00%3A00%3A00%2B00%3A00&posted__lt=2017-07-06+00%3A00%3A00%2B00%3A00 HTTP/1.1" 200 10055[0m
[05/Jul/2017 08:12:34] [m"GET /admin/jsi18n/ HTTP/1.1" 200 3189[0m
[05/Jul/2017 08:12:38] [m"GET /admin/posts/post/1/change/?_changelist_filters=q%3Dmutton%26last_updated__gte%3D2017-07-05%2B00%253A00%253A00%252B00%253A00%26posted__gte%3D2017-07-05%2B00%253A00%253A00%252B00%253A00%26last_updated__lt%3D2017-07-06%2B00%253A00%253A00%252B00%253A00%26posted__lt%3D2017-07-06%2B00%253A00%253A00%252B00%253A00 HTTP/1.1" 200 5384[0m
[05/Jul/2017 08:12:38] [m"GET /admin/jsi18n/ HTTP/1.1" 200 3189[0m
[05/Jul/2017 08:12:38] [36m"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:38] [36m"GET /static/admin/js/change_form.js HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:39] [m"GET /admin/posts/post/?q=mutton&last_updated__gte=2017-07-05+00%3A00%3A00%2B00%3A00&posted__gte=2017-07-05+00%3A00%3A00%2B00%3A00&last_updated__lt=2017-07-06+00%3A00%3A00%2B00%3A00&posted__lt=2017-07-06+00%3A00%3A00%2B00%3A00 HTTP/1.1" 200 10055[0m
[05/Jul/2017 08:12:51] [m"GET /admin/posts/ HTTP/1.1" 200 2189[0m
[05/Jul/2017 08:12:51] [36m"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:51] [36m"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:51] [36m"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0[0m
[05/Jul/2017 08:12:53] [m"GET /admin/posts/post/ HTTP/1.1" 200 7308[0m
[05/Jul/2017 08:12:53] [m"GET /admin/jsi18n/ HTTP/1.1" 200 3189[0m
Performing system checks...

System check identified some issues:

WARNINGS:
[33;1m?: (urls.W001) Your URL pattern '^posts/$' uses include with a regex ending with a '$'. Remove the dollar from the regex to avoid problems including URLs.[0m
[33;1m?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace[0m

System check identified 2 issues (0 silenced).
July 05, 2017 - 09:33:47
Django version 1.11.3, using settings 'trydjango19.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fc414d01730>
Traceback (most recent call last):
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/karan/djangoSandbox/trydjango19/src/trydjango19/urls.py", line 21, in <module>
    url(r'^posts/$', posts.views.post_home),
NameError: name 'posts' is not defined
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f1f3e457730>
Traceback (most recent call last):
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/karan/djangoSandbox/trydjango19/src/trydjango19/urls.py", line 21, in <module>
    url(r'^posts/$', "posts.views.post_home"),
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 85, in url
    raise TypeError('view must be a callable or a list/tuple in the case of include().')
TypeError: view must be a callable or a list/tuple in the case of include().
^C[1m[7m%[27m[1m[0m                                                                                ]2;karan@karUbuntu: ~/djangoSandbox/trydjango19/src]1;..ydjango19/src[0m[27m[24m[J(trydjango19) [01;32mâžœ  [36msrc[00m [K[?1h=[?2004hpython manage.py runserver[?1l>[?2004l
]2;python manage.py runserver]1;pythonPerforming system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f426e131730>
Traceback (most recent call last):
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/karan/djangoSandbox/trydjango19/src/trydjango19/urls.py", line 21, in <module>
    from posts import views as posts_views
  File "/home/karan/djangoSandbox/trydjango19/src/posts/views.py", line 7
    request HttpResponse("<h1>HELLO!</h1>")
                       ^
SyntaxError: invalid syntax
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2017 - 09:45:19
Django version 1.11.3, using settings 'trydjango19.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Not Found: /post
[05/Jul/2017 09:45:27] [33m"GET /post HTTP/1.1" 404 2068[0m
[05/Jul/2017 09:45:31] [32m"GET /posts HTTP/1.1" 301 0[0m
[05/Jul/2017 09:45:31] [m"GET /posts/ HTTP/1.1" 200 15[0m
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7feeff975730>
Traceback (most recent call last):
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/karan/djangoSandbox/trydjango19/src/trydjango19/urls.py", line 31, in <module>
    url(r'^posts/', include("posts.urls")),
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'posts.urls'
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f9e39b9c730>
Traceback (most recent call last):
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/karan/djangoSandbox/trydjango19/src/trydjango19/urls.py", line 31, in <module>
    url(r'^posts/', include("posts.urls")),
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/karan/djangoSandbox/trydjango19/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/karan/djangoSandbox/trydjango19/src/posts/urls.py", line 6, in <module>
    url(r'^$', views.post_home, name='posts'),
AttributeError: module 'posts.views' has no attribute 'post_home'
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2017 - 10:04:48
Django version 1.11.3, using settings 'trydjango19.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Not Found: /posts/create
[05/Jul/2017 10:05:05] [33m"GET /posts/create HTTP/1.1" 404 2823[0m
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2017 - 10:06:22
Django version 1.11.3, using settings 'trydjango19.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[05/Jul/2017 10:06:27] [32m"GET /posts/create HTTP/1.1" 301 0[0m
[05/Jul/2017 10:06:27] [m"GET /posts/create/ HTTP/1.1" 200 15[0m
[05/Jul/2017 10:06:37] [m"GET /posts/update/ HTTP/1.1" 200 15[0m
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2017 - 10:09:25
Django version 1.11.3, using settings 'trydjango19.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2017 - 10:09:27
Django version 1.11.3, using settings 'trydjango19.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2017 - 10:11:26
Django version 1.11.3, using settings 'trydjango19.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[05/Jul/2017 10:11:34] [m"GET /posts/update/ HTTP/1.1" 200 15[0m
[05/Jul/2017 10:11:40] [m"GET /posts/ HTTP/1.1" 200 13[0m
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2017 - 10:17:04
Django version 1.11.3, using settings 'trydjango19.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2017 - 10:23:45
Django version 1.11.3, using settings 'trydjango19.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[05/Jul/2017 10:23:53] [m"GET /posts/ HTTP/1.1" 200 111[0m
Performing system checks...

System check identified no issues (0 silenced).
July 05, 2017 - 10:43:49
Django version 1.11.3, using settings 'trydjango19.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[05/Jul/2017 10:44:19] [m"GET /posts/ HTTP/1.1" 200 117[0m
Not Found: /detail
[05/Jul/2017 10:44:30] [33m"GET /detail HTTP/1.1" 404 2059[0m
^C[1m[7m%[27m[1m[0m                                                                                ]2;karan@karUbuntu: ~/djangoSandbox/trydjango19/src]1;..ydjango19/src[0m[27m[24m[J(trydjango19) [01;32mâžœ  [36msrc[00m [K[?1h=[?2004heexit[?1l>[?2004l
]2;exit]1;exit
Script done on Wednesday 05 July 2017 04:55:32 PM IST
